import streamlit as st

st.title("Society & Culture")

st.subheader("Free Tickets for Sports Games")
st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3YnHpelw9bAPijequjBTsvM_H4G6xoPrWoA&s")
st.write("Sports are a part of human society and people shouldn’t have to pay to go to games.")
st.markdown("#")

st.subheader("Free-to-air Sports Games")
st.write("DO:")
st.image("https://nbcsports.brightspotcdn.com/dims4/default/fe43efd/2147483647/strip/false/crop/599x337+0+0/resize/599x337!/quality/90/?url=https%3A%2F%2Fnbc-sports-production-nbc-sports.s3.us-east-1.amazonaws.com%2Fbrightspot%2F9e%2F33%2F174253e8713c0345fe2eb70de05e%2Fcfnp4zxumaef99h.jpg")
st.write("DO NOT:")
st.image("https://nbcsports.brightspotcdn.com/dims4/default/e806518/2147483647/strip/true/crop/1920x1080+0+0/resize/1440x810!/quality/90/?url=https%3A%2F%2Fnbc-sports-production-nbc-sports.s3.us-east-1.amazonaws.com%2Fbrightspot%2F58%2F93%2F39d56d46488fbb2754975f59fe21%2Fchampionship-sunday-2025.png")
st.write("When companies put games on streaming platforms you must pay to watch. If they were also free on streaming platforms than that would be fine. As stated earlier people should not have to pay to watch games that are important to them. Sports are a big part of people's lives and making them pay is criminal.")
st.markdown("#")
st.subheader("Mental Health & Well Being")
st.write("The country allows you to deal with your problems you way, except for crime.")
st.markdown("#")
st.subheader("Crime")
st.write("Active murder will mean the death sentence")
st.write("Everything else with mean 1-20 years of jail time.")
st.write("***THIS APPLIES TO ALL PEOPLE***")
st.markdown("#")
st.subheader("Free Public Schools and Paid Private Schools")
st.write("Public School")
st.image("https://imagescdn.homes.com/i2/P35eYUq9i82O-7uOrMmXQIYtLlxP6zPhYlLgBKkw1oo/117/p-s-290-manhattan-new-school-new-york-ny-primaryphoto.jpg?p=1")
st.write("Private School")
st.image("https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Dwight_School_291_CPW_jeh.JPG/250px-Dwight_School_291_CPW_jeh.JPG ")
st.write("The reason to have both free public schools and paid private schools is because some people don’t have the money for private schools, but sometimes public schools don’t have enough support systems, and because they don’t always get you into the best universities.")
st.markdown("#")

st.subheader("Cars")
st.write("No Cars on the streets from 11PM- 5AM. People need sleep and cars speeding past peoples homes will not help them sleep")
st.write("No more than two cars per household. The reason for this is that less cars means less pollution")
st.image("https://www.roadtrafficsigns.com/img/lg/K/No-Car-Symbol-Sign-K-5331.gif")
st.markdown("#")

st.subheader("Free Dance Parties every Friday Night!")
st.write("Why not dance? Dancing is fun. It makes life fun, and when life isn’t fun it gets dark.")
st.image("https://images.stockcake.com/public/8/5/0/8503a3e1-2ac0-4d88-8c6f-dda5aff5bab5_large/vibrant-dance-party-stockcake.jpg")
st.markdown("#")

st.subheader("Hosting")
st.write("Once in someone’s life they must host the current presidents.")
st.write("When someone finally hosts the presidents they get a tax exemption for the next year.")
st.image("https://media.hswstatic.com/eyJidWNrZXQiOiJjb250ZW50Lmhzd3N0YXRpYy5jb20iLCJrZXkiOiJnaWZcLzEwLXdheXMtdGF4LWV4ZW1wdDEtMS5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjgyOH19fQ==")
st.markdown("#")

st.subheader("Independence Day")
st.write("May 6th will be National Independence Day")
st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRx7t0Fl93AxGsZMI8kM4u2yqWpwKfkujk5vg&")
st.markdown("#")

st.subheader("Nationality")
st.write("The people will be known as the Rafkonians")
st.write("Everyone is to say Rafkon forever")